# Generated by Django 4.1.6 on 2023-02-03 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя официанта', max_length=150, verbose_name='Имя официанта:')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название бизнеса.', max_length=150, unique=True, verbose_name='Название:')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='Логотип:')),
                ('color', models.CharField(max_length=150, verbose_name='Цвет приложения:')),
                ('domain', models.CharField(help_text='Этот параметр будет использоваться для авторизации', max_length=300, verbose_name='Доменное имя для бизнеса:')),
                ('owner', models.CharField(help_text='Введите имя владельца.', max_length=150, verbose_name='Владелец:')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Почта владельца.')),
                ('owner_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
