# Generated by Django 4.1.6 on 2023-02-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование:')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название блюда', max_length=150, unique=True, verbose_name='Наименование:')),
                ('description', models.CharField(max_length=400, verbose_name='Описание:')),
                ('composition', models.CharField(max_length=400, verbose_name='Состав блюда:')),
                ('price', models.FloatField(help_text='Введите цену', max_length=10, verbose_name='Цена блюда:')),
                ('discountPrice', models.FloatField(help_text='Введите цену', max_length=10, verbose_name='Дисконтная цена:')),
                ('currency', models.CharField(max_length=150, verbose_name='Валюта:')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='Внешний вид блюда:')),
                ('is_popular', models.BooleanField(help_text='☑ - востребованно, ▢ - не востребованно', verbose_name='Востребованность блюда:')),
            ],
        ),
        migrations.CreateModel(
            name='QRCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=1000000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('hashsalt', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание для стола:')),
            ],
        ),
    ]
