# Generated by Django 4.1.6 on 2023-02-14 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='table',
            field=models.ForeignKey(help_text='Выберите стол', on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='menu.tables', verbose_name='Стол:'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dishes',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию блюда', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='menu.categories', verbose_name='Категория блюда:'),
        ),
        migrations.AddField(
            model_name='categories',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
