# Generated by Django 4.1.6 on 2023-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tables',
            name='hashsalt',
            field=models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
