# Generated by Django 4.1.6 on 2023-02-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_categories_business_dishes_business_qrcodes_business_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='category_id',
            new_name='category',
        ),
    ]
