# Generated by Django 3.2.10 on 2023-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='id',
            field=models.IntegerField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
