# Generated by Django 4.1.6 on 2023-02-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.CharField(db_index=True, help_text='Этот параметр будет использоваться для авторизации', max_length=300, unique=True, verbose_name='Доменное имя для бизнеса:'),
        ),
    ]
