# Generated by Django 4.1.6 on 2023-02-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, db_index=True, help_text='Этот параметр будет использоваться для авторизации', max_length=300, verbose_name='Доменное имя для бизнеса:'),
        ),
    ]
